# Generated by Django 3.2.25 on 2025-08-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='totla_cost',
            field=models.FloatField(default=0),
        ),
    ]
