# Generated by Django 3.2.25 on 2025-09-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20250902_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='card',
            new_name='cart',
        ),
    ]
