# Generated by Django 3.2.25 on 2025-09-02 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_cart_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theowner', to=settings.AUTH_USER_MODEL),
        ),
    ]
